### ISSUE TITLE
Create Controller and Services for Venues

### ISSUE THREAD

**Issue by DLittlefield81** [iPlayed-games/backend#17]

**Comment by DanielMJSilva** [comment]
I created the following files for venue:

- Controller: getAllVenues and  getOneVenueById
- Service: getAllVenues and getVenueById
- Route: venueRouter

All Venues:

![Image](https://github.com/iPlayed-games/backend/assets/70338659/cd136444-1e6f-4178-9a59-4b52b1262789)

Venue by Id:


![Image](https://github.com/iPlayed-games/backend/assets/70338659/d6506239-eb2e-4bd4-b93e-bdc589acb6c2)
