### ISSUE TITLE
update flow chart and database ERD

### ISSUE THREAD

**Issue by rmc3408** [iPlayed-games/backend#18]
Acceptance Criteria:

1- User flow diagram for homePage - DONE
2 - Update Database based on the new homepage design

**Comment by rmc3408** [comment]
Please review part 1 only in tab homePage in link [drawio](https://app.diagrams.net/#G1EcEML3q8ObomGcZjH0liFS6zKG7V7-fc#%7B%22pageId%22%3A%22M82R6eiU_Z0B-IXj1-f4%22%7D)

**Comment by DanielMJSilva** [comment]
Reviewed. All good.
