### ISSUE TITLE
Create ERD for Activities

### ISSUE THREAD

**Issue by rmc3408** [iPlayed-games/backend#3]

**Comment by rmc3408** [comment]
![Image](https://github.com/iPlayed-games/backend/assets/64808456/1c7f1532-898c-4708-b8d4-c86570dd62b9)

Link for file
https://drive.google.com/file/d/1EcEML3q8ObomGcZjH0liFS6zKG7V7-fc/view?usp=sharing

**Comment by rmc3408** [comment]
@DanielMJSilva , this is database for HomePage, hope nothing is missing. Can you approve?

**Comment by DanielMJSilva** [comment]
Approved
