### ISSUE TITLE
create Controller and Services for Auth(user)

### ISSUE THREAD

**Issue by rmc3408** [iPlayed-games/backend#35]

**Comment by JWMedeiros** [comment]
Acceptance Criteria:

1, Add /auth route in app.ts
2. Create authRoute.ts and link to app.ts
3. Create authController.ts and link to authRoute.ts
4. Create authService.ts
5. Create auth.ts that will handle authentication in a later ticket.

**Comment by rmc3408** [comment]
I will say on create router

/auth/login
/auth/signup
